version: '3.8'

services:
  web:
    build: .
    container_name: dwui_web
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - agent
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DATABASE_URL: ${DATABASE_URL}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}

  agent:
    build:
      context: ./agent
    container_name: dwui_agent
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8001:8000"
