# Generated by Django 5.1.7 on 2025-03-25 20:58
from __future__ import annotations

from typing import TYPE_CHECKING

from django.db import migrations, models

if TYPE_CHECKING:
    from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    """Migration to add AdminSettings model."""

    dependencies: list[tuple[str, str]] = [
        ("dwui", "0001_initial"),
    ]

    operations: list[Operation] = [
        migrations.CreateModel(
            name="AdminSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("site_name", models.CharField(max_length=100)),
                ("admin_email", models.EmailField(max_length=254)),
                ("enable_notifications", models.BooleanField(default=False)),
            ],
        ),
    ]
