# Generated by Django 5.1.7 on 2025-03-28 04:03
from __future__ import annotations

from typing import TYPE_CHECKING

from django.db import migrations, models

if TYPE_CHECKING:
    from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    """Migration class for altering fields in the dwui app.

    This migration modifies the following fields:
    - config.application_setup: Don't allow null values.
    - config.networking: Don't allow null values.
    - linuxserver.project_logo: Don't allow null values.
    - linuxserver.project_url: Don't allow null values.
    """

    dependencies: list[tuple[str, str]] = [
        ("dwui", "0002_alter_config_application_setup_and_more"),
    ]

    operations: list[Operation] = [
        migrations.AlterField(
            model_name="config",
            name="application_setup",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="config",
            name="networking",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="linuxserver",
            name="project_logo",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="linuxserver",
            name="project_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
