# Generated by Django 5.1.7 on 2025-03-29 03:57
from __future__ import annotations

from typing import TYPE_CHECKING

from django.db import migrations, models

if TYPE_CHECKING:
    from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    """Migration to add default_config_path and default_data_path fields to AdminSettings."""

    dependencies: list[tuple[str, str]] = [
        ("dwui", "0003_alter_config_application_setup_and_more"),
    ]

    operations: list[Operation] = [
        migrations.AddField(
            model_name="adminsettings",
            name="default_config_path",
            field=models.TextField(blank=True, default="", help_text="Default path for container configuration storage (e.g., NVMe)"),
        ),
        migrations.AddField(
            model_name="adminsettings",
            name="default_data_path",
            field=models.TextField(blank=True, default="", help_text="Default path for container data storage (e.g., HDD)"),
        ),
    ]
