# Generated by Django 5.1.7 on 2025-03-26 04:43
from __future__ import annotations

from typing import TYPE_CHECKING

from django.db import migrations, models

if TYPE_CHECKING:
    from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    """Migration to remove the id field from AdminSettings and add site_id."""

    dependencies: list[tuple[str, str]] = [
        ("dwui", "0003_remove_adminsettings_admin_email_and_more"),
    ]

    operations: list[Operation] = [
        migrations.RemoveField(
            model_name="adminsettings",
            name="id",
        ),
        migrations.AddField(
            model_name="adminsettings",
            name="site_id",
            field=models.AutoField(default=1, help_text="Site ID", primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
