# Generated by Django 5.1.7 on 2025-03-30 14:43
from __future__ import annotations

from typing import TYPE_CHECKING

from django.db import migrations, models

if TYPE_CHECKING:
    from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    """Migration to add default_uid and default_gid fields to AdminSettings model."""

    dependencies: list[tuple[str, str]] = [
        ("dwui", "0005_remove_linuxserver_architectures_remove_config_caps_and_more"),
    ]

    operations: list[Operation] = [
        migrations.AddField(
            model_name="adminsettings",
            name="default_gid",
            field=models.IntegerField(default=1000, help_text="Default group ID for container operations"),
        ),
        migrations.AddField(
            model_name="adminsettings",
            name="default_uid",
            field=models.IntegerField(default=1000, help_text="Default user ID for container operations"),
        ),
    ]
