name: Build and Push Agent Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  schedule:
      - cron: '0 0 * * *' # Runs every day at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: 'build-agent'
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: agent/Dockerfile
          push: ${ github.event_name != 'pull_request' }
          tags: ghcr.io/TheLovinator1/dwui-agent:latest
